# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
  name: SelfHostedAgent

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'  # Choose the appropriate Python version

- script: |
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest
    python -m pytest
  displayName: 'Run pytest'

